# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "solve360"
  s.version = "0.0.11"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Bartholomew"]
  s.date = "2012-07-18"
  s.description = ""
  s.email = "Stephen Bartholomew"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/solve360.rb",
    "lib/solve360/company.rb",
    "lib/solve360/config.rb",
    "lib/solve360/contact.rb",
    "lib/solve360/item.rb",
    "spec/api_settings.yml.sample",
    "spec/fixtures/contacts/create-success.json",
    "spec/fixtures/contacts/find-all.json",
    "spec/fixtures/contacts/find-company-success.json",
    "spec/fixtures/contacts/find-success.json",
    "spec/fixtures/contacts/index.json",
    "spec/fixtures/contacts/save-failed.json",
    "spec/fixtures/contacts/show-success.json",
    "spec/fixtures/contacts/update-success.json",
    "spec/solve360/item_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/curve21/solve360"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Libary for working with the Solve360 CRM API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configify>, [">= 0.0.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<httmultiparty>, [">= 0"])
    else
      s.add_dependency(%q<configify>, [">= 0.0.1"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<httmultiparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<configify>, [">= 0.0.1"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<httmultiparty>, [">= 0"])
  end
end

